baseurl      = "https://00derek.github.io"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Father // Husband // Athelete // Software engineer // Voracious reader"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

   # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  # footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  # footerRight = "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.portrait]
    path     = "images/profile.jpg"
    alt      = "Portrait"
    maxWidth = "240px"

    # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/derek0627"

  [[params.social]]
    name = "email"
    url  = "mailto:derekchang@live.com"

  [[params.social]]
    name = "github"
    # url = "https://github.com/00derek"
    url = "https://github.com/derek-chang-exa"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/chihweichang"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Just Random Notes"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Thinking, Fast and Slow"
      logoHomeLink = "/"
    # or
    #
    # path = "images/profile.jpg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
